package ru.nstu.system.contracts.events;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * Envelope shared by every domain event (design.md D13, D14).
 *
 * <p>The envelope is immutable and Jackson-serialisable. {@code eventId} doubles
 * as the RabbitMQ correlation id, {@code eventType} is used as the routing key
 * and {@code version} allows additive evolution of the payload contract.</p>
 *
 * @param eventId    globally unique event identifier, generated by the producer
 * @param eventType  one of the constants in {@link EventTypes}; also the routing key
 * @param version    payload contract version, currently {@link EventTypes#CURRENT_VERSION}
 * @param occurredAt instant the domain fact happened
 * @param payload    event-specific body
 * @param <T>        payload type
 */
public record DomainEvent<T>(
        @JsonProperty("eventId") UUID eventId,
        @JsonProperty("eventType") String eventType,
        @JsonProperty("version") int version,
        @JsonProperty("occurredAt") Instant occurredAt,
        @JsonProperty("payload") T payload) {

    public DomainEvent {
        Objects.requireNonNull(eventId, "eventId must not be null");
        Objects.requireNonNull(eventType, "eventType must not be null");
        Objects.requireNonNull(occurredAt, "occurredAt must not be null");
    }

    /**
     * Convenience factory for the common case: fresh id, current version and
     * current instant.
     */
    public static <T> DomainEvent<T> of(String eventType, T payload) {
        return new DomainEvent<>(
                UUID.randomUUID(), eventType, EventTypes.CURRENT_VERSION, Instant.now(), payload);
    }
}
